<?php echo $this->doctype(); ?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Album '. $this->translate('Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                    ->appendStylesheet($this->basePath() . '/css/bootstrap.min.css')
                    ->appendStylesheet($this->basePath() . '/css/style.css')
                    ->appendStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css') ?>

    <!-- Scripts -->
    <?php echo $this->headScript()->appendFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                  ->appendFile($this->basePath() . '/js/jquery-1.7.2.min.js') ?>

  </head>

  <body>
    <div class="wrapper">
        <div class="header-container">
			<div class="header">
                <div class="navbar navbar-fixed-top">
                  <div class="navbar-inner">
                    <div class="container">
                      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">

                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                      </a>
                      <a class="brand" href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Skeleton Application') ?></a>
                      <div class="nav-collapse">
                        <ul class="nav">
                          <li class="active"><a href="<?php echo $this->url('home') ?>"><?php echo $this->translate('Home') ?></a></li>
                          <li class="active"><a href="<?php echo $this->url('album',array('action'=>'detail')) ?>"><?php echo $this->translate('Detail') ?></a></li>
                          <!-- <li class="active"><a href="<?php echo $this->url('album',array('action'=>'artist')) ?>"><?php echo $this->translate('Artist') ?></a></li> -->
                        </ul>
                      </div><!--/.nav-collapse -->
                    </div>
                  </div>
                </div>
            </div>
		</div>

        <div class="container col2-layout">
            <div class="main">
                    <?php echo $this->lowercase();?>
                    <?php echo $this->content; ?>
			</div>
        </div> <!-- /container -->
        <div class="footer-container">
			<div class="footer">footer</div>
		</div>
    </div>

  </body>
</html>
<script type="text/javascript">
    // $(document).ready(function(){
    //         $('a').click(function() {
    //                 var val = $(this).text();
    //                 alert(val);
    //         });
    // });
</script>
